[package]
name = "tree-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.37"
clap = "4.5.4"
# serde = "1.0.203"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tempfile = "3.10.1"
