name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, beta, nightly]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Rust
      uses: actions/checkout@v4.1.1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}

    - name: Install dependencies
      run: cargo fetch

    - name: Build and Test
      run: cargo build --verbose && cargo test --verbose
